### ISSUE TITLE
thread safe

### ISSUE THREAD

**Issue by sunyueyin** [smallnest/weighted#1]
rand.NewSource is not a thread safe api, i think it is necessary to describe about it in the roundbin_weigth.go:Next()

**Comment by hypnoglow** [comment]
BTW, even not mentioning `rand.NewSource`, this library is NOT thread safe, as `Next()` method of `SW`/`RRW` modifies struct properties without any mutexes or other concurrency primitives.

IMHO implementing synchronization is crucial. Of course it will hit the performance, but otherwise this library is unusable on its own. 

In the meantime, as a workaround, it can be used with external synchronization mechanisms:
```golang
type SafeSW struct {
	origin *weighted.SW
	mx     sync.Mutex
}

func (sw *SafeSW) Next() interface{} {
	sw.mx.Lock()
	defer sw.mx.Unlock()

	return sw.origin.Next()
}
```

**Comment by smallnest** [comment]
Thanks. Added Notice to indicate weighted it NOT goroutine-safe.
